spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB # max 50 mb upload on server
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/